### PR TITLE
Grammar, spelling and sentence structure changes

### PR DESCRIPTION
**Pull request by camisatx**
Hey Prakhar! :)

A little later than I expected, but I'm happy that I was able to finish going over the entire guide (which I did find excellent!).

For the most part, I only change spelling, punctuation and grammar. I aimed for good sentence flow.

I added some links for busybox and the hub (138), along with fixing an outdated link (136). Speaking of outdated links, I checked 95% of them and they are all still good. When linking to the hub, I changed the existing link to go to the explore page because I feel like it's more applicable than the main page (https://hub.docker.com/explore/).

And I added the 3.0 section header to Multi-Container Environment header (473).

As always, do look over my suggestions and let me know if you see anything off.

### CODE REVIEW

**Comment by prakhar1989** [comment]
Hey @camisatx, thanks for sending in those fixes. Really appreciate it. I'll go over these and let you know if anything requires a change. Thanks again!

**Comment by camisatx** [comment]
Awesome Prakhar. Happy to help!

**Comment by prakhar1989** [comment]
Finally got a chance to read this through (final exams just ended - phew!) 

This looks great! Thank for finding so many errors 💃  Merging this now! 🎆

**Comment by camisatx** [comment]
Yay! What better to do on a Friday night than complete merge requests. Haha. Thanks for checking and merging it.

So we can now expect some amazing summer projects from you? :wink:

**Comment by prakhar1989** [comment]
Haha @camisatx. :D

**Pull request merged**
